CREATE TABLE BRANCH
(
    BRANCH_ID         UUID PRIMARY KEY,
    BRANCH_SHORT_NAME varchar(45)  NOT NULL,
    BRANCH_NAME       varchar(100) NOT NULL,
    DESCRIPTION       varchar(200) DEFAULT NULL
-- ,
   -- JSON_DATA JSON
);


CREATE TABLE BRANCH_INFO
(
    BRANCH_INFO_ID         SERIAL PRIMARY KEY,
    BRANCH_INFO_DATA       varchar(100) NOT NULL,
    BRANCH_ID  UUID REFERENCES BRANCH (BRANCH_ID)
);

CREATE TABLE SUBJECT
(
    SUBJECT_ID   SERIAL PRIMARY KEY,
    SUBJECT_NAME varchar(100) NOT NULL,
    SUBJECT_DESC varchar(200) DEFAULT NULL,
    BRANCH_ID  UUID REFERENCES BRANCH (BRANCH_ID)
);

